#! /bin/bash
set -e -u

# non tools.pywikibot should not be able to tamper with this
umask 0022

# Create version file
function create_version {
    echo "$1" > $2
    git rev-list HEAD | wc -l >> $2
    date +%Y-%m-%dT%H:%M:%S >> $2
    git rev-parse --short HEAD >> $2
}

TMPDIR=$(mktemp -d)
echo Building new public_html in $TMPDIR on `hostname`...
function finish {
  rm -rf "$TMPDIR"
  echo Cleaned up $TMPDIR
}
trap finish EXIT

cd $TMPDIR

echo Step 1: mwparserfromhell
git -c advice.detachedHead=false clone -q --depth 1 -b v0.6.5 https://github.com/earwig/mwparserfromhell.git
(cd mwparserfromhell && python3 setup.py -q build && git gc --aggressive --prune=all --quiet)

echo Step 2: setuptools T284299
git -c advice.detachedHead=false clone -q --depth 1 -b v68.0.0 https://github.com/pypa/setuptools.git
(cd setuptools && python3 setup.py -q build && git gc --aggressive --prune=all --quiet)

echo Step 3: core master
# Current version of core
git clone -q --depth 1 https://gerrit.wikimedia.org/r/pywikibot/core.git
(cd core
    create_version "nightly/core" "pywikibot/version"
    git gc --aggressive --prune=all --quiet
    (cd scripts
        git clone -q --depth 1 https://gerrit.wikimedia.org/r/pywikibot/i18n.git
        (cd i18n && git gc --aggressive --prune=all --quiet)
    )
    cp -a ../mwparserfromhell/build/lib*/. .
    cp -a ../setuptools/build/lib*/. .
    (cd setuptools && ln -s ../pkg_resources . && ln -s ../_distutils_hack .)
)

echo Step 4: core stable
# Create a stable version of core. Bugs T98592 and T217236
git clone -q --depth 1 -b stable https://gerrit.wikimedia.org/r/pywikibot/core.git core_stable
(cd core_stable
    create_version "nightly/core_stable" "pywikibot/version"
    git gc --aggressive --prune=all --quiet
    (cd scripts
        git clone -q --depth 1 https://gerrit.wikimedia.org/r/pywikibot/i18n.git
        (cd i18n && git gc --aggressive --prune=all --quiet)
    )
    cp -a ../mwparserfromhell/build/lib*/. .
    cp -a ../setuptools/build/lib*/. .
    (cd setuptools && ln -s ../pkg_resources . && ln -s ../_distutils_hack .)
)

echo Step 6: zip ALL the things
zip -9 -r -q core.zip core
zip -9 -r -q core_stable.zip core_stable

echo Step 7: tar ALL the things
tar czPf core.tar.gz core/
tar czPf core_stable.tar.gz core_stable/

echo Step 8: copy static files
cp -R /data/project/pywikibot/public_html_static/. .

echo Step 9: do the magic switcharoo
set 
cd /data/project/pywikibot/
rm -rf public_html.new
rm -rf public_html.old
mv $TMPDIR public_html.new
chmod 755 public_html.new
mv public_html public_html.old
mv public_html.new public_html
