#! /bin/bash
set -e -u

# Create version file
function create_version {
    echo "$1" > $2
    git rev-list HEAD | wc -l >> $2
    date +%Y-%m-%dT%H:%M:%S >> $2
    git rev-parse --short HEAD >> $2
}

TMPDIR=$(mktemp -d)
echo Building new public_html in $TMPDIR on `hostname`...
function finish {
  rm -rf "$TMPDIR"
  echo Cleaned up $TMPDIR
}
trap finish EXIT

cd $TMPDIR

echo Step 1: mwparserfromhell
git clone -q https://github.com/earwig/mwparserfromhell.git
(cd mwparserfromhell && git gc --aggressive --prune=all --quiet)

echo Step 2: compat
# compat
git clone -q --recursive --depth 1 https://gerrit.wikimedia.org/r/pywikibot/compat.git
(cd compat
    create_version "nightly/compat" "version"
    git gc --aggressive --prune=all --quiet
    (cd i18n && git gc --aggressive --prune=all --quiet)
)

echo Step 3: core master
# Current version of core
git clone -q --depth 1 https://gerrit.wikimedia.org/r/pywikibot/core.git
(cd core
    create_version "nightly/core" "pywikibot/version"
    git gc --aggressive --prune=all --quiet
    (cd scripts
        git clone -q --depth 1 https://gerrit.wikimedia.org/r/pywikibot/i18n.git
        (cd i18n && git gc --aggressive --prune=all --quiet)
    )
    cp -R ../mwparserfromhell/mwparserfromhell/ mwparserfromhell/
)

echo Step 4: core-7 days old
#Create an old version of core. Bug T98592
git clone -q https://gerrit.wikimedia.org/r/pywikibot/core.git core_old
(cd core_old
    git checkout $(git rev-list -n 1 --before=`date --date="7 days ago" +%F` master) -b core_old
    create_version "nightly/core_old" "pywikibot/version"
    git gc --aggressive --prune=all --quiet
    (cd scripts
        git clone -q --depth 1 https://gerrit.wikimedia.org/r/pywikibot/i18n.git
        (cd i18n && git gc --aggressive --prune=all --quiet)
    )
    cp -R ../mwparserfromhell/mwparserfromhell/ mwparserfromhell/
)

echo Step 5: core-stable
#Create 2.0 version
git clone -q --depth 1 -b 2.0 https://gerrit.wikimedia.org/r/pywikibot/core.git core_stable
(cd core_stable
    create_version "nightly/core_stable" "pywikibot/version"
    git gc --aggressive --prune=all --quiet
    (cd externals
        git clone -q --depth 1 https://gerrit.wikimedia.org/r/pywikibot/externals/httplib2.git
        (cd httplib2 && git gc --aggressive --prune=all --quiet)
    )
    (cd scripts
        git clone -q --depth 1 https://gerrit.wikimedia.org/r/pywikibot/i18n.git
        (cd i18n && git gc --aggressive --prune=all --quiet)
    )
    cp -R ../mwparserfromhell/mwparserfromhell/ mwparserfromhell/
)

echo Step 6: zip ALL the things
zip -9 -r -q core.zip core
zip -9 -r -q core_old.zip core_old
zip -9 -r -q core_stable.zip core_stable
zip -9 -r -q compat.zip compat

echo Step 7: tar ALL the things
tar czPf core.tar.gz core/
tar czPf core_old.tar.gz core_old/
tar czPf core_stable.tar.gz core_stable/
tar czPf compat.tar.gz compat/

echo Step 7: copy static files
cp -R /data/project/pywikibot/public_html_static/* .

echo Step 8: do the magic switcharoo
set 
cd /data/project/pywikibot/
rm -rf public_html.new
rm -rf public_html.old
mv $TMPDIR public_html.new
mv public_html public_html.old
mv public_html.new public_html
